spring:
  profiles:
    active: development
---
spring:
  profiles: development
  h2:
    console:
      enabled: true
  security:
    user:
      name: user
      password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
