spring:
  profiles:
    active: development
---
spring:
  profiles: development
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    initialization-mode: embedded